### ISSUE TITLE
Small Typo of Weather.scala in Japanese version doc

### ISSUE THREAD

**Issue by kirinsannnnnnnnnn** [sbt/website#1024]
`//` in markdown in [source](https://github.com/sbt/website/blob/develop/src/reference/ja/00-Getting-Started/02-sbt-by-example.md#play-json-%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6-json-%E3%82%92%E3%83%91%E3%83%BC%E3%82%B9%E3%81%99%E3%82%8B) is displayed as `/` on [website in browser](https://www.scala-sbt.org/1.x/docs/ja/sbt-by-example.html#Play+JSON+%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6+JSON+%E3%82%92%E3%83%91%E3%83%BC%E3%82%B9%E3%81%99%E3%82%8B), therefore `core/src/main/scala/example/core/Weather.scala` will be fail.

[English version](https://github.com/sbt/website/blob/develop/src/reference/00-Getting-Started/02-sbt-by-example.md#parse-json-using-play-json) is escaping the character correctly.

I would appreciate it if you fix it when you have a time.

**Comment by eed3si9n** [comment]
Looks like the English version was fixed in https://github.com/sbt/website/pull/767

**Comment by eed3si9n** [comment]
っていうか、`//` じゃなくて Scala が `\\` にならなきゃいけないので、 Pamflet (StringTemplate 4) だと `\\\\` とバックスラッシュ4枚使いする必要があるよっていう話ですね。報告ありがとうございます。
