### ISSUE TITLE
Broken link in Organizing Build page

### ISSUE THREAD

**Issue by EdgeCaseBerg** [sbt/website#103]
If you go the the [Organizing Build](http://www.scala-sbt.org/release/tutorial/Organizing-Build.html) page,  and ctrl+f for "ld is to define one-off auto plugins in" The link to auto plugins is broken. What is this supposed to point to? I can submit a pull request with it fixed if someone can tell me where it's supposed to go.

**Comment by eed3si9n** [comment]
http://www.scala-sbt.org/0.13/docs/Plugins.html I think.

**Comment by EdgeCaseBerg** [comment]
Created #104 with the link updated.

**Comment by eed3si9n** [comment]
Thanks for the PR btw!
