### ISSUE TITLE
Search results are under body

### ISSUE THREAD

**Issue by ckipp01** [sbt/website#1031]
On the current site when attempting to use the search functionality, the search results appear under the main body.

![2021-07-13 13 23 08](https://user-images.githubusercontent.com/13974112/125443751-980d29d9-35e0-4fe9-b5bd-1b8cdedb3785.gif)

Tried on both Chrome and Firefox with the same result

**Comment by eed3si9n** [comment]
I'm guessing it's something to do with https://github.com/sbt/website/pull/1027

**Comment by ericdotdata** [comment]
Toggling the `overflow-x: hidden` makes it show up again

**Comment by er1c** [comment]
https://github.com/sbt/website/pull/1038

**Comment by eed3si9n** [comment]
@er1c I guess that fixes the documentation, but not the landing pages.

**Comment by er1c** [comment]
> @er1c I guess that fixes the documentation, but not the landing pages.

Let me figure out howto run this all locally, because it seemed to work on the landing pages for me when I was just toggling inside debuger

**Comment by er1c** [comment]
This is working now: https://www.scala-sbt.org/ (might have to clear cache)

**Comment by eed3si9n** [comment]
Thanks!
