### ISSUE TITLE
See download instructions for all platforms independent of from where you surf

### ISSUE THREAD

**Issue by bjornregnell** [sbt/website#1037]
I have quite a few students who run ubuntu under WSL. They surf using their Windows browser to the sbt home page and get the instructions for Windows, but they want to know how to install sbt under linux. 

I think the sbt download page should have a button or something for selecting platform so you can surf from one platform and see the instructions for another.

**Comment by eed3si9n** [comment]
Now that WSL is becoming more popular, that makes sense.
