### ISSUE TITLE
scala-sbt.org hosts an outdated copy of the sbt-native-packager documentation

### ISSUE THREAD

**Issue by SethTisue** [sbt/website#1072]
at https://github.com/sbt/sbt-native-packager/issues/1459#issuecomment-1076160694, @atais noticed that e.g. https://www.scala-sbt.org/sbt-native-packager/gettingstarted.html has outdated information

the current doc lives at https://sbt-native-packager.readthedocs.io/en/latest/

so I think https://www.scala-sbt.org/sbt-native-packager/ should be taken offline?

**Comment by eed3si9n** [comment]
I think this is automatically created when sbt-native-packager publishes GitHub Pages. They could remove `gh-pages` branch, or change some setting?
https://github.com/sbt/sbt-native-packager/tree/gh-pages

**Comment by SethTisue** [comment]
okay I opened https://github.com/sbt/sbt-native-packager/issues/1504
