### ISSUE TITLE
Followed a link, got a 404

### ISSUE THREAD

**Issue by 0x2f0x00** [sbt/website#1109]
This was the link:  https://www.scala-sbt.org/release/docs/Detailed-Topics/Proxy-Repositories.html

It was on [this StackOverflow post](https://stackoverflow.com/questions/3770125/how-do-i-get-sbt-to-use-a-local-maven-proxy-repository-nexus) from the front page of a Google search for "self hosted SBT package repository"

**Comment by eed3si9n** [comment]
Around Dec 19, 2021 (https://github.com/sbt/sbt/issues/6757) GitHub Pages stopped supporting symlinks, so I removed symlinks in https://github.com/sbt/sbt.github.com/commit/433ce271914dcb3654113f59d41ce71031c4487a and now Googling for it, looks like they fixed it next day https://github.com/community/community/discussions/9104

**Comment by eed3si9n** [comment]
Should be fixed now.

**Comment by eed3si9n** [comment]
ok, now I think it's fixed.
