### ISSUE TITLE
Repository's Packages.gz is out-of-date

### ISSUE THREAD

**Issue by dasoumao** [sbt/website#1127]
# steps
1. Use apt to install  sbt.
# problem
1. The newest version of sbt from https://scala.jfrog.io/ui/native/debian/Packages.gz is 1.4.9.
# expectation
please update the repository's Packages.gz.

**Comment by eed3si9n** [comment]
See https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html#Ubuntu+and+other+Debian-based+distributions

```
echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
```

I don't know much about Debian, but I am guessing that the new package is now https://scala.jfrog.io/ui/native/debian/dists/all/main/binary-all/
