### ISSUE TITLE
Anchors hide the top of the section below the floating header

### ISSUE THREAD

**Issue by dwijnand** [sbt/website#117]
Try and click http://www.scala-sbt.org/0.13/docs/Best-Practices.html#.sbtrc and the .sbtrc part won't be visible as it's below the floating header (Docs/Download/Get Involved).

**Comment by eed3si9n** [comment]
Let me make the community label.

**Comment by eed3si9n** [comment]
`window.scrollBy(0, 100)` scrolls 100 pixels
