### ISSUE TITLE
Broken link to sbt documentation and API

### ISSUE THREAD

**Issue by jeffmay** [sbt/website#1186]
On the [Learn | sbt](https://www.scala-sbt.org/learn) page, the following link is broken:

* [sbt API](https://www.scala-sbt.org/$sbtVersionForScalaDoc$/api/sbt/index.html)

It looks like the `$sbtVersionForScalaDoc$` variable is not being substituted correctly.

**Comment by tech189** [comment]
The links to the documentation and the pdf are also broken:
- https://www.scala-sbt.org/learn/1.x/docs/sbt-reference.pdf
- https://www.scala-sbt.org/learn/1.x/docs/index.html

There's an extra `learn` in the url
