### ISSUE TITLE
Broken website on https://www.scala-sbt.org/index.html

### ISSUE THREAD

**Issue by grzegorz-bielski** [sbt/website#1187]
<img width="1887" alt="Screenshot 2024-02-09 at 09 27 26" src="https://github.com/sbt/website/assets/22674545/478b2c8b-0bbe-4863-ba02-74052c9052c6">

Looks like the `div` with `main-wrapper` class is added twice to the website body.

Works fine with https://www.scala-sbt.org, but [old docs](https://www.scala-sbt.org/1.x/docs/) are redirecting to the https://www.scala-sbt.org/index.html, so it might be surprising for some people.

**Comment by eed3si9n** [comment]
Thanks for the report!

**Comment by bishabosha** [comment]
really couldn't find much assistance from Docusaurus docs about this

**Comment by bishabosha** [comment]
actually if you go to https://docusaurus.io/index.html they have the exact same issue

**Comment by bishabosha** [comment]
I've now opened https://github.com/facebook/docusaurus/issues/9871 because it seems it was not reported before

**Comment by bishabosha** [comment]
looks like this isn't fixable without configuring github pages static routing (is that possible?):
https://github.com/facebook/docusaurus/issues/9871#issuecomment-1954641623

its out of my knowledge area anyway
