### ISSUE TITLE
Landing page https://www.scala-sbt.org/ is down

### ISSUE THREAD

**Issue by sebastian-alfers** [sbt/website#1233]

**Comment by eed3si9n** [comment]
Thanks. I think I broke it when I deleted `docs/` directory that Docusaurus wants.

**Comment by eed3si9n** [comment]
Hopefully this will fix - https://github.com/sbt/website/pull/1234

**Comment by eed3si9n** [comment]
https://www.scala-sbt.org/ seems to be back.

**Comment by sebastian-alfers** [comment]
🙇
