### ISSUE TITLE
`The book of sbt` dark mode contains hard to read figures

### ISSUE THREAD

**Issue by Friendseeker** [sbt/website#1262]
### Issue

<img width="784" alt="image" src="https://github.com/user-attachments/assets/27efec43-b3c1-4e5f-95ad-a6b688174298" />

Figures like above are unreadable

### Expected

Figures should all be easily readable

### Note

We probably need to raise the contrast? Or invert the color of the diagram?

**Comment by eed3si9n** [comment]
I didn't want the dark theme to be selected, but when I added the language bar, the code that I copied from somewhere included a line about using OS's prefers-color-scheme.
