### ISSUE TITLE
segfault while installing sbt via apt-get

### ISSUE THREAD

**Issue by kjarnet** [sbt/website#127]
This issue was initially posted to sbt/sbt: https://github.com/sbt/sbt/issues/1883

The documentation says to run the following commands to install on ubuntu

    echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
    sudo apt-get update
    sudo apt-get install sbt

If you do that, then you will get the following crash.

    NV\sowen@kafka01:~$ echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
    ...
    ...
    NV\sowen@kafka01:~$ sudo apt-get update
    NV\sowen@kafka01:~$ sudo apt-get install sbt
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    The following NEW packages will be installed:
      sbt
    0 upgraded, 1 newly installed, 0 to remove and 24 not upgraded.
    Need to get 1,041 kB of archives.
    After this operation, 1,224 kB of additional disk space will be used.
    WARNING: The following packages cannot be authenticated!
      sbt
    Install these packages without verification? [y/N] y
    E: Method https has died unexpectedly!
    E: Sub-process https received a segmentation fault.

Downloading the deb-file manually and installing with dpkg works fine. See:
http://stackoverflow.com/questions/13711395/install-sbt-on-ubuntu/13718915#13718915
http://stackoverflow.com/questions/28543911/sbt-install-failure-with-aptitude-on-ubuntu-14-04

Either the documentation should be updated, or a key should be included with the package. 

Answer to original bug from jsuereth:
> It looks like bintray recently starting having issues with HTTPs. Suprised it's a segfault. In any case, please reopen this against sbt/website.

**Comment by ostefano** [comment]
I'd strongly suggest to reopen the issue here, forcing http is a really bad idea :/
Also, packages should be signed.
Correct solution would be to publish the key and sign the packages.

**Comment by eed3si9n** [comment]
@ostefano There's a case for fixing this #132

**Comment by ostefano** [comment]
@eed3si9n thx. posting there.
