### ISSUE TITLE
Scaladoc API documentation is missing

### ISSUE THREAD

**Issue by michaelpigg** [sbt/website#129]
The [Documentation](http://www.scala-sbt.org/documentation.html) page links to http://www.scala-sbt.org/0.13.8/api/index.html for API docs, but there is nothing there.

**Comment by eed3si9n** [comment]
This is due to doc aggregation and macros. We'll have to downgrade to 0.13.7 for now.

**Comment by dwijnand** [comment]
@eed3si9n Can you expand more on that please? What's the issue?

**Comment by eed3si9n** [comment]
@dwijnand Docs from subprojects are aggregated using sbt-unidoc. This effectively bundles all source code into a single flat path and passes it to scaladoc. This seems to break some of the macros.
I opened sbt/sbt-unidoc#20 too.

**Comment by dwijnand** [comment]
I see, thanks.

**Comment by eed3si9n** [comment]
This might actually be Pickling related. scala/pickling#369

**Comment by eed3si9n** [comment]
I think I've figured this out. To generate Scaladoc for macros, typically `"-Ymacro-no-expand"` is added into the options. Pickling generates an implicit value for `FastTypeTag[A]` using a macro. Without it pickler implicits are not created. A workaround is to add:

```scala
  implicit def fakeFastTypeTag[T]: FastTypeTag[T] = ???
```

in the erring blocks.

**Comment by dwijnand** [comment]
Feels like `-Ymacro-no-expand` should always be in `scalacOptions` when generating scaladocs by default. What do you think?

Actually, we could add it by default in sbt, but maybe it should be by default in scala itself?

**Comment by xuwei-k** [comment]
fixed in https://github.com/sbt/website/commit/9cab836f11d2aa2fcc ?

**Comment by dwijnand** [comment]
Yep, thanks Kenji.
