### ISSUE TITLE
Old documentations should link to the new one

### ISSUE THREAD

**Issue by eed3si9n** [sbt/website#134]
People still frequently cites old doc. Maybe because the version lookup shows 0.13.5 as the latest.
Regardless, we should probably point at newer doc.

**Comment by ktoso** [comment]
I'm happy to help out on that, since we rolled out such a thing for Akka: http://doc.akka.io/docs/akka/2.3.1/general/actor-systems.html

By looking at the repo for a few minutes I was unable to figure out where the old pages live, how are those published (where would I need to apply the fixes)?

**Comment by eed3si9n** [comment]
The old stuff should be here - https://github.com/sbt/sbt.github.com

**Comment by ktoso** [comment]
Ah I see, thanks! I'll prep a PR over the next days I hope.

**Comment by dwijnand** [comment]
Done in https://github.com/sbt/website/commit/e5adeb5879d08a98620e3c712681e60fc17eb68b or thereabouts on the master branch.

**Comment by ktoso** [comment]
Hah nice, I'm sorry I never got around doing it as I offered. Too spread out...

Kudos on making it happen!

**Comment by dwijnand** [comment]
Santa Yokota-san to the rescue :)
