### ISSUE TITLE
Make SBT_OPS information page in Getting Started

### ISSUE THREAD

**Issue by taisukeoe** [sbt/website#135]
We (cc @takezoux2 ) see common mistakes of sbt beginners who don't set SBT_OPS in our regular Scala meetups. Then, as you imagine, their sbt immediately run out of memory. 

This is because recommended SBT_OPS setting was only written in [Installing sbt manually](http://www.scala-sbt.org/0.13/tutorial/Manual-Installation.html) page among [Getting Started with sbt](http://www.scala-sbt.org/0.13/tutorial/index.html) pages, while it should be relevant for all ways of installation (at least homebrew's). So people who have installed sbt in homebrew rarely see `Installing sbt manually` page and often misses SBT_OPS.

So we propose to make "recommended sbt options" page separate from [Installing sbt manually](http://www.scala-sbt.org/0.13/tutorial/Manual-Installation.html), or put SBT_OPS information to all `Installing sbt xxx` pages.

If it's OK for you, we're happy to send pull requests as well.

**Comment by eed3si9n** [comment]
If the default values in the `sbt` launch script is broken by default, that's something we need to fix, not just the documentation.
For Linux and Mac, I think our launcher script tries to add default memory options (https://github.com/sbt/sbt-launcher-package/blob/a80410996f368937e94161227fa9ecdad0f363e5/src/universal/bin/sbt-launch-lib.bash#L75-L92). I'm not sure about Windows. Are the people having these issues using Windows?

/cc @jsuereth

**Comment by taisukeoe** [comment]
Thank you very much for your clarifications.
Indeed it's not a document problem. It can be launcher script problem or Xmx amount problem.

They were using Mac and homebrew to install sbt. Though we didn't check if the launcher script really works on their mac or not, we let them to add SBT_OPTS and solve OutOfMemoryError. However, at this moment we couldn't reproduce this OutOfMemoryError so far on our Mac even using docker.

Since this issue is finally not a document problem, I think this issue should be closed and we should go to sbt issues after we reproduced or clarified this problem. Is it OK for you?

cc/ @takezoux2

**Comment by eed3si9n** [comment]
If you can reproduce the issue, the best project to submit the bug for the launcher script would be [sbt/sbt-launcher-package](https://github.com/sbt/sbt-launcher-package).
