### ISSUE TITLE
Opinion: TOC on the side rather than bottom

### ISSUE THREAD

**Issue by metasim** [sbt/website#140]
I found having the TOC on the right side in the old docs format much easier to navigate than having to scroll to the bottom of each page. It was also easier to keep track of where one was when jumping between sections. Not sure if Pamflet supports it, but having a more "Sphinx-style" TOC would improve usability in my opinion.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/website/pull/760
