### ISSUE TITLE
Jenkins, instead of Travis

### ISSUE THREAD

**Issue by eed3si9n** [sbt/website#176]
we should automate pushing new websites.

**Comment by dwijnand** [comment]
Travis should be able to do it too. There's prior art of people publishing snapshots from builds on master.

**Comment by eed3si9n** [comment]
The problem is that we are downloading gigs of stuff for latex while building pdf that fails iirc.

**Comment by SethTisue** [comment]
http://docs.travis-ci.com/user/caching/ could address that?

**Comment by eed3si9n** [comment]
@SethTisue caching doesn't work because the latex download requires sudo apt-get stuff.

**Comment by SethTisue** [comment]
and those modules aren't on the apt whitelist...?

**Comment by SethTisue** [comment]
just opened 3 days ago: https://github.com/travis-ci/apt-source-whitelist/issues/55

**Comment by eed3si9n** [comment]
Nice. If that happens, I'm happy to stay on Travis for website publishing.

**Comment by ashawley** [comment]
Upgrading from Ubuntu 12 to Ubuntu 14 helped with getting a newer (more i18n'd?) texlive distro

**Comment by eed3si9n** [comment]
I'll close this up since Travis is looking better.
