### ISSUE TITLE
Title of the download page is broken

### ISSUE THREAD

**Issue by metc** [sbt/website#209]
Hello,

The title page of the current online download page is not displayed at all. This bug appears from [this commit](https://github.com/sbt/sbt.github.com/commit/fbd9c967016d53557925e4c35eb263d08564aa43#diff-75f3d75b2f1caade24ced34b49384a1fR6).

I looked at the [default layout](https://github.com/sbt/website/blob/master/src/nanoc/layouts/default.html#L56) and at the [download page content](https://github.com/sbt/website/blob/master/src/nanoc/content/download.html#L2), but I was not able to find any problem.
I am not familiar with `ruby` and `nanoc`, so I was not able to create a PR to fix it directly, sorry.

**Comment by eed3si9n** [comment]
I pushed the site of off a wip/nanoc branch. The issues is now fixed by @Saisse in #210 and merged to master.

**Comment by metc** [comment]
Thanks @eed3si9n :+1:
