### ISSUE TITLE
Linux downloads not shown

### ISSUE THREAD

**Issue by Sciss** [sbt/website#229]
I was just told that there exists an architecture switch on the `download` page. This doesn't seem to work on Linux (Debian 8, Iceweasel/Firefox 38). Inspecting the page, all platforms are greyed out instead of showing the Linux bit.

![screenshot from 2016-03-09 00 01 30](https://cloud.githubusercontent.com/assets/131300/13619623/74829ec2-e58a-11e5-91f6-04df051b0a81.png)

Info from http://mybrowserinfo.com:

```
Your Browser User Agent String is Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.6.1
Operating System:
    Linux
Platform:
    UNIX
Internet Browser:
    Firefox 38.0
```

**Comment by ashawley** [comment]
This was fixed last year in #258
