### ISSUE TITLE
nav is slightly irritating

### ISSUE THREAD

**Issue by tpolecat** [sbt/website#24]
In a reasonably-sized browser window the "go left" and "go right" regions take up about 25% of the width of the window and it's really easy to click over to the next or previous page as you're mousing around. At least for me; I do it every single time I look at the doc. What would you think about maybe just making the buttons hot instead of the entire margin?

**Comment by dwijnand** [comment]
:+1: I'm constantly having to go back in the browser after randomly switching pages by mistake..

**Comment by eed3si9n** [comment]
At some point I got rid of the page nav.
