### ISSUE TITLE
https (https://www.scala-sbt.org/ uses Github's cert)

### ISSUE THREAD

**Issue by eed3si9n** [sbt/website#275]
https://github.com/isaacs/github/issues/156

**Comment by SethTisue** [comment]
is this the ticket of record on ''Google results are returning HTTPS instead of HTTP now, but the certificate is for github, not for scala-sbt"?

**Comment by eed3si9n** [comment]
Maybe it's time we consider moving to somewhere else like S3.

**Comment by Ichoran** [comment]
My first hit on Google for `sbt subproject` is

> **sbt Reference Manual — Multi-project builds**
https://www.scala-sbt.org/0.13/docs/Multi-Project.html
Each subproject in a build has its own source directories, generates its own jar ... as the subproject's ID, which is used to refer to the subproject at the sbt shell.

I get similar results with other queries.

**Comment by dwijnand** [comment]
Alternatively we could reverse things and redirect from scala-sbt.org to (I guess) https://sbt.github.io/website

**Comment by dwijnand** [comment]
Oh actually I guess it's simply https://sbt.github.io

**Comment by eed3si9n** [comment]
We can probably use https://www.cloudflare.com.

**Comment by dwijnand** [comment]
Sorted: https://www.scala-sbt.org/

**Comment by dwijnand** [comment]
GitHub has started rolling this out: https://github.com/isaacs/github/issues/156#issuecomment-366504568 so we could switch back to them.

**Comment by dwijnand** [comment]
steps to migrate back to GitHub (from https://github.com/isaacs/github/issues/156#issuecomment-380159640):

1. Remove the CNAME from the old repo.
2. Make sure your DNS is directed directly to GitHub pages and not a CDN.
3. Create a new repo with a different name.
4. Push your files to this new repo. DO NOT push the CNAME file with this. If you push the CNAME file here, enforce HTTPS gets disabled.
5. Now go to settings for the new repo and enable GitHub pages. Wait for the site to build and check.
6. Now add a CNAME through the settings.
7. Wait for HTTPS to set up (takes ~2 minutes) and have fun!
