### ISSUE TITLE
Put the recommended platform installers on the download page

### ISSUE THREAD

**Issue by seglo** [sbt/website#278]
I use Linux, so the current download instructions on http://www.scala-sbt.org/download.html are fine for me, but I think the other recommended platform installers should be front and center on this page as well.  They should be above the fold when browsing the page on a common desktop resolution.

I realize the links are available as part of the docs (http://www.scala-sbt.org/0.13/docs/Setup.html), but linking directly to the Windows, OSX, and Linux install instructions would make for a better UX (a few less clicks and scrolling).

**Comment by eed3si9n** [comment]
Note that the download page changes contents depending on the platform you browse.
For me (using Mac) it says:

```
Homebrew (Third-party package)
$ brew install sbt
```

**Comment by seglo** [comment]
Ah, of course.  My mistake.  I was attempting to find setup instructions for another platform for another individual.  I didn't consider there would be a user agent switch.  

I'll close the ticket.
