### ISSUE TITLE
Migrate to Paradox

### ISSUE THREAD

**Issue by dwijnand** [sbt/website#281]
https://github.com/lightbend/paradox

Prerequisite:
- [ ] https://github.com/lightbend/paradox/issues/154 Globalisation/localisation support
- [ ] https://github.com/lightbend/paradox/issues/14 PDF generation support

**Comment by eed3si9n** [comment]
Paradox doesn't support globalization or PDF generation yet.

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-contrib/blob/fdfc651f429aac3d4f2a543e3108ed1cc6cc9ed9/src/main/markdown/2017-11-08.md#103

> Website is now updated. I was close to remove Nanoc, and use Paradox. We will come back to this.
