### ISSUE TITLE
doc version menu: choosing "latest version" gives you 1.0

### ISSUE THREAD

**Issue by SethTisue** [sbt/website#302]
if this was even intentional (?), it doesn't seem like a good idea to me. 1.0 isn't out yet. I would suggest that "latest version" give me the docs for 0.13.13

not sure whether these should be separate tickets, but:

* I would also suggest dropping everything but 0.7.7, 0.12.4, and 0.13
* it's _really_ confusing that doc versions "0.13" and "0.13.5" are offered but "0.13" is actually newer than 0.13.5, since "0.13" is actually "latest 0.13.x"

**Comment by eed3si9n** [comment]
It was intentional, but you're right on all points.

**Comment by eed3si9n** [comment]
The list is now limited to 0.7.7, 0.12.4, and 0.13 - https://github.com/sbt/website/commit/890cae47e65037d53c545f05322862b7bb9aab06

To mitigate the 0.13.5 confusion, I'm borrowing the warning callout from Akka's doc:
- https://github.com/sbt/website/commit/e5adeb5879d08a98620e3c712681e60fc17eb68b
- https://github.com/sbt/sbt.github.com/commit/50229c6047cdf58fa0c0c3017616f61ec49f56fc

![welcome__ _sbt_documentation](https://cloud.githubusercontent.com/assets/184683/21466658/f5193858-c99f-11e6-9d36-49680837ebdd.png)

**Comment by SethTisue** [comment]
I love the big yellow warning, well done!

**Comment by eed3si9n** [comment]
An interesting side effect of removing everything but 0.7.7, 0.12.4, and 0.13 is that if you did end up on 1.0 beta document via Google, there's no way to go to the actual latest 0.13.
