### ISSUE TITLE
website: Scaladoc link still points to 0.13.15

### ISSUE THREAD

**Issue by SethTisue** [sbt/website#303]
at http://www.scala-sbt.org/documentation.html , both the "sbt API" and "source" links still point to 0.13.12. should be 0.13.13

just updating the links isn't enough, the 0.13.13 stuff actually doesn't exist (not at the corresponding URLs anyway)

**Comment by SethTisue** [comment]
I'm interested in seeing this fixed. can I help? if it were just a matter of submitting a PR in this repo I would do it, but afaict it isn't that simple.

**Comment by eed3si9n** [comment]
yea. There's a special weird branch that changes the source around to generate docs and xray.

**Comment by dwijnand** [comment]
Scaladoc fails IIRC. So first step would he to reproduce and report the failure, as clearly I didn't do the due diligence to create an issue for it. Thanks Seth. We want to get 0.13.14 soonish.

**Comment by SethTisue** [comment]
handling it as part of 0.13.14 sounds totally fine to me

**Comment by eed3si9n** [comment]
It's that or `doc` task is more sensitive to warning than the command line Scaladocs, or something like that. My hack branch is https://github.com/eed3si9n/sbt/commits/topic/generate_doc

**Comment by dwijnand** [comment]
> Scaladoc fails IIRC. So first step would he to reproduce and report the failure, as clearly I didn't do the due diligence to create an issue for it. Thanks Seth. We want to get 0.13.14 soonish.

Hey. Apparently I sometimes do remember to do the due diligence. See https://github.com/sbt/sbt/issues/2812 for the reproduction and errors.

**Comment by SethTisue** [comment]
these links now point to 0.13.15, should point to 0.13.16

(and as before, it isn't just wrong links... the targets don't exist)

**Comment by dwijnand** [comment]
I fixed sbt/sbt#2812 btw in sbt/sbt#3401, but that was after we cut 0.13.16. I'm hoping that that means that with the release of 0.13.17 this should be fixes, @eed3si9n? I haven't been following what's been going on with scaladocs and xrays of sbt on the website.

**Comment by dwijnand** [comment]
FWIW in the 1.x docs the API docs correctly to 1.0.2.

Hopefully with the 0.13.17 release we can fix the 0.13 links.

**Comment by SethTisue** [comment]
0.13.x series is dead, so I'll just close this.
