### ISSUE TITLE
HTML Link Broken

### ISSUE THREAD

**Issue by co-category** [sbt/website#305]
HTML link to Project type is broken in:

https://github.com/sbt/website/blob/master/src/reference/00-Getting-Started/05-Basic-Def.md

**Comment by ashawley** [comment]
It's a relative link.  When the page is rendered with pamflet it produces a link to the apidocs for `Project` that works for me.

http://www.scala-sbt.org/0.13/docs/Basic-Def.html

Was that the issue?

**Comment by dwijnand** [comment]
@ashawley is correct, the intent is for the link to work when rendered in scala-sbt.org.

We don't cater for the documentation being read via GitHub.
