### ISSUE TITLE
Remove sbt 1.0 docs, or print warning that it's a pre-released docs

### ISSUE THREAD

**Issue by eed3si9n** [sbt/website#320]
Debian/Ubuntu users are confused because the installation instruction points them to experimental stuff.

**Comment by dwijnand** [comment]
Do you mean "or" instead of "for"?

I'm happy to remove it, it'll need a proper revising for 1.0, it's just confusing/wrong atm.

**Comment by eed3si9n** [comment]
Maybe rename to 1.0-beta/ and tell Google to not index?

**Comment by dwijnand** [comment]
Personally I would remove it. We can use read the sources for now until we've reviewed it.

**Comment by eed3si9n** [comment]
When the beta comes out though I would like a place to document new features, changes, list of plugins etc.

**Comment by dwijnand** [comment]
Yeah, when we're ready for the beta we should definitely bring it back, with accurate information.

**Comment by dwijnand** [comment]
sbt 1.0 is out.

**Comment by Masood-Iqlect** [comment]
I'm getting this error " unable to locate sbt package"

**Comment by eed3si9n** [comment]
@Masood-Iqlect please open a new issue on sbt/sbt following the instruction here - https://www.scala-sbt.org/community.html#how-can-I-help
