### ISSUE TITLE
experiemental rpm install instructions broken

### ISSUE THREAD

**Issue by benmccann** [sbt/website#321]
The rpm install instructions are broken on http://www.scala-sbt.org/1.0/docs/Installing-sbt-on-Linux.html
https://bintray.com/sbt/rpm/rpm-experimental results in a 404

 I think the real URL is supposed to be https://bintray.com/sbt/rpm-experimental ?

**Comment by dwijnand** [comment]
Imo, it's not so much as "the instructions are broken", more that we've not yet made binary pre-releases of sbt 1.0, so there's nothing there.

See also #320.

**Comment by benmccann** [comment]
Ahhh. Ok. In that case I'll close this. I thought there'd be a milestone release there or something
