### ISSUE TITLE
Automate publishing

### ISSUE THREAD

**Issue by dwijnand** [sbt/website#326]
Merging changes should automatically publish the documentation.

This is related to #176, except that ticket is about moving to Jenkins, while I'm just talking about automating publishing.

**Comment by eed3si9n** [comment]
We really should work on automating this (without spewing keys to public).

**Comment by dwijnand** [comment]
I agree.

**Comment by ashawley** [comment]
It's possible with Travis.

- https://docs.travis-ci.com/user/deployment/pages/
- https://docs.travis-ci.com/user/encryption-keys/

sbt web site has a sophisticated upload set up, but it could probably still be done with Travis config.

**Comment by dwijnand** [comment]
Done with #381, @eed3si9n?

**Comment by eed3si9n** [comment]
Now it's done!

- http://eed3si9n.com/auto-publish-from-travis-ci
