### ISSUE TITLE
migration guide for sbt-012x incomplete, need to mention `task`

### ISSUE THREAD

**Issue by vn971** [sbt/website#351]
Hi all. This migration guide: http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html  is probably a bit incomplete.

It turns out migration doesn't cover code that relied on `Task[T]`. Consider, for example, this code:

```scala
resourceGenerators in Compile <+= (resourceManaged, baseDirectory) map { (managedBase, base) =>
	val webappBase = base / "src" / "main" / "webapp"
 	for {
 		(from, to) <- webappBase ** "*" pair rebase(webappBase, managedBase / "main" / "webapp")
 	} yield {
 		Sync.copy(from, to)
 		to
 	}
}
```

You can't really change it to `+=` and `.value` invocations because it was previously a `Task[Seq[File]]`, and now you'll get `Seq[File]`. What you actually _should_ do is wrap the code with `task {}`. So this is the solution I've come to for my code:

```scala
resourceGenerators in Compile += task {
	val webappBase = sourceDirectory.value / "main" / "webapp"
	val managedBase = resourceManaged.value
 	for {
 		(from, to) <- webappBase ** "*" pair rebase(webappBase, managedBase / "main" / "webapp")
 	} yield {
 		Sync.copy(from, to)
 		to
 	}
}
```

What I am suggesting is to enrich the migration guide with info about `Task`.
Telling that if you previously had a `Task[T]` and now getting the `T` itself, consider wrapping the code with `task {}` to get the previous behavior back.

I think that would be helpful especially when migrating to sbt-1.0.0 (which removes the method `<+=`).
Thanks.

**Comment by dwijnand** [comment]
The section of the guide where we try and help on this is http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html#Migrating+when+you+need+to+set+s

But we can definitely take your feedback here and improve it. Thank you for opening this issue.

**Comment by jvican** [comment]
Good find @vn971, I'll implement this in https://github.com/scalacenter/sbt-migration-rewrites.

**Comment by eed3si9n** [comment]
In sbt 1.0 `+=` operator is able to accept `Def.task { ... }`  https://github.com/sbt/sbt/pull/2942.
This change is backported to 0.13.14 that will come out soon.

I've just clarified that in the migration guide - http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html#Migrating+when+you+need+to+set+s

**Comment by vn971** [comment]
@eed3si9n Thanks! Note that the thing I write about is the other way around. I have a code that generates value (`T`), and I want to create a task out of it (so I have to wrap it with `task {}`).

**Comment by dwijnand** [comment]
I propose this is fixed given this section in http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html#Migrating+when+you+need+to+set+s:

> or in general,
>
> ```
> sourceGenerators in Compile += Def.task { List(file1, file2) }
> ```
