### ISSUE TITLE
Linux install instructions verbose?

### ISSUE THREAD

**Issue by ScalaWilliam** [sbt/website#352]
The Linux install instructions ([GitHub](https://github.com/sbt/website/blob/5d6453ba7c8154ff759be43ed748c38910b27935/src/reference/00-Getting-Started/01-Setup/c.md), [scala-sbt.org](http://www.scala-sbt.org/release/docs/Installing-sbt-on-Linux.html)) are verbose,
such as the paragraph containing "but usually you don’t install your software from a local DEB file" could be replaced with a link to a more qualified external resource or simply removed.

When I installed the first few times, I would stop to read something I already knew as a Linux user :-)

The screenshot for "Software & Updates" is not entirely necessary either. There is an imbalance against the very concise Windows & Mac installation instructions.

Any comments and suggestions before I make a pull request for slimming down the instructions?
I think of covering the whole page.

**Comment by eed3si9n** [comment]
These instructions were added over time (for example via https://github.com/sbt/website/pull/80) for reasons. If you want the spartan style, http://www.scala-sbt.org/0.13.2/docs/Getting-Started/Setup.html#installing-sbt is how it used to look for linux back then:

> - RPM package
> - DEB package

Even the developers who are familiar with Mac and Windows occasionally need to handle Linux machines for production or CI environments, and having more verbose info helps.

**Comment by ScalaWilliam** [comment]
All right, thanks for the explanation!

I understand and won't be making a PR. Closing.
