### ISSUE TITLE
Debian package repository incorrect

### ISSUE THREAD

**Issue by alexandradeas** [sbt/website#384]
As mentioned in https://github.com/sbt/sbt/issues/2928 the current guide for installation is incorrect as it's specifying `debian-experimental` which currently returns a 404. An update for the guide to `echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list` would resolve issue for debian based distros.

**Comment by dwijnand** [comment]
Fixed as a part of #434 (16266fff8d59d78bff008dd3176ddc8e74e67b40 specifically).
