### ISSUE TITLE
Decide what the version granularity of the docs

### ISSUE THREAD

**Issue by dwijnand** [sbt/website#408]
(Kind of related to sbt/sbt#3231 "Redirect sbt documentation for 0.12.x")

Currently we have the following documentation "roots":
+ http://www.scala-sbt.org/0.13/docs/index.html
+ http://www.scala-sbt.org/1.0/docs/index.html
+ http://www.scala-sbt.org/0.12.4/docs/index.html

Should we perhaps change the "1.0" one to "1" or "1.x"? Or do we intend to have different doc sites per feature releases?

**Comment by ashawley** [comment]
If previous sbt development is any indicator, I presume the next major release is 1.1 (and not 1.1.0 and not 2.0 either).   So using "1.0" in the path to documentation seems appropriate and sufficient.  Going forward, the 1.0 documentation will be archived, and the next release will be documented as "1.1"?

**Comment by eed3si9n** [comment]
> If previous sbt development is any indicator, I presume the next major release is 1.1 (and not 1.1.0 and not 2.0 either).

I never know what major/minor means, but sbt will adopt Semantic Versioning.

- 1.x series will keep bincompat until 2.0
- New features will be added in 1.1.0+
- Bug fixes in 1.0.x.

As with 0.13, the docs will be a mutable one that should live throughout the 1.x lifetime, and thus should be renamed to 1.x.

**Comment by ashawley** [comment]
Ok then. I guess the past isn't an indicator of the future.

**Comment by dwijnand** [comment]
I don't think it's worked: http://www.scala-sbt.org/1.x/docs/Community-Plugins.html

Also I expected the need for a bunch of redirects, or some invocation for batch redirecting 1.0 -> 1.x.

**Comment by eed3si9n** [comment]
Travis is still deploying. Once it's done I'm going to make a symbolic link.

**Comment by dwijnand** [comment]
ok

**Comment by eed3si9n** [comment]
Done https://github.com/sbt/sbt.github.com/commit/d64915b6e3ba31c5c1a05a184de82378087dffcd
