### ISSUE TITLE
Remove "External Processes" from 1.x doc

### ISSUE THREAD

**Issue by bpholt** [sbt/website#427]
Since https://github.com/sbt/util/commit/4629053277afb703829ca2b586d4b4ed12e35e17, `sbt.ProcessBuilder` seems to have been removed. However, https://github.com/sbt/website/blob/1.x/src/reference/02-DetailTopics/02-Configuration/12-Process.md still references it. This page should be updated to reflect the new way to execute external processes. 

(Maybe `sbt.ProcessBuilder` has just been moved, not removed altogether, but if so, I couldn't find it. Unfortunately, I don't know what the new way of running external processes is.)

**Comment by eed3si9n** [comment]
It's moved to http://www.scala-lang.org/api/2.12.x/scala/sys/process/index.html.

We should update the docs accordingly.

**Comment by dwijnand** [comment]
Fixed in #429.
