### ISSUE TITLE
0.13 docs don't link to 1.0.x

### ISSUE THREAD

**Issue by raboof** [sbt/website#527]
When on http://www.scala-sbt.org/0.13/docs/index.html it seems like you're on the 'Latest version', even though you're not.

**Comment by Philippus** [comment]
there's an option missing on:
https://github.com/sbt/sbt.github.com/blob/master/1.x/docs/index.html#L107
and
https://github.com/sbt/sbt.github.com/blob/master/0.13/docs/index.html#L105

the option is there on:
https://github.com/sbt/sbt.github.com/blob/master/0.12.4/docs/index.html#L83

`set-versions.js` depends on the option to do its magic

**Comment by eed3si9n** [comment]
Related I sent in https://github.com/sbt/website/pull/507 to display outdated warning, but closed it because we thought it's still too soon.

**Comment by Philippus** [comment]
closed by sbt/website#541 and related PR's
