### ISSUE TITLE
helper link redirection to 404 page

### ISSUE THREAD

**Issue by satyakonidala** [sbt/website#529]
**page address**: http://www.scala-sbt.org/1.x/docs/Basic-Def.html

**content**: _A build definition is defined in build.sbt, and it consists of a set of projects (of type [Project](http://www.scala-sbt.org/1.x/api/sbt/Project.html)). Because the term project can be ambiguous, we often call it a subproject in this guide._

**problem**: clicking on hyperlink of project leads to a 404 page

**Comment by dwijnand** [comment]
Related to @dec5e's efforts in https://github.com/sbt/website/pull/526 and https://github.com/sbt/sbt.github.com/pull/42

**Comment by dec5e** [comment]
Continuing efforts to fix links in #530 😄

**Comment by dwijnand** [comment]
Fixed with #530, thanks to the tireless @dec5e :D
