### ISSUE TITLE
Specific version of pandoc.

### ISSUE THREAD

**Issue by jiminhsieh** [sbt/website#564]
Since `pandoc 2.0.0`, it renamed `--latex-engine` to `--pdf-engine`. There is [the release note of pandoc 2.0.0](https://pandoc.org/releases.html#behavior-changes). I guess it would be better to indicate which version we use. Or maybe we could update argument of `pandoc`, in the meantime, we could document the version we use.

**Comment by eed3si9n** [comment]
cool.

I am also happy to make PDF building optional, if ppl mostly are building web locally.

**Comment by jiminhsieh** [comment]
I found the version of pandoc and TeX Live in Travis CI are quite old. Pandoc's version is `1.12.2.1`. And TeX Live's version is `TeX Live 2013`. I don't know if it's a good idea to update. I also noticed this ticket - [Migrate to Paradox](https://github.com/sbt/website/issues/281). I guess the best way to handle this is to document in the README and wait for the migration to paradox.

**Comment by eed3si9n** [comment]
Local Pandoc on my machine is now 2.0.6, so I had to make the following change locally:

```diff
     def latexArgs(language: String): Seq[String] =
       language match {
-        case "ja" => Seq("-V", "documentclass=ltjarticle", "--latex-engine=lualatex")
-         case _ => Seq("--latex-engine=xelatex")
+        case "ja" => Seq("-V", "documentclass=ltjarticle", "--pdf-engine=lualatex")
+         case _ => Seq("--pdf-engine=xelatex")
       }
```
