### ISSUE TITLE
some image resources 404 in non-English pages

### ISSUE THREAD

**Issue by xuwei-k** [sbt/website#594]
## http://www.scala-sbt.org/1.x/docs/index.html

<img width="169" alt="English-Page" src="https://user-images.githubusercontent.com/389787/35393638-e4b58cec-0228-11e8-84b6-6278af96c73b.png">

<hr />

## http://www.scala-sbt.org/1.x/docs/ja/index.html

<img width="965" alt="Japanese-Page" src="https://user-images.githubusercontent.com/389787/35393639-e4e134f0-0228-11e8-81e2-8448021d858f.png">

**Comment by eed3si9n** [comment]
Probably https://raw.githubusercontent.com/sbt/website/1.x/src/reference/ja/layouts/header.md became out of sync?
