### ISSUE TITLE
Update latest version to 1.1.1

### ISSUE THREAD

**Issue by dwijnand** [sbt/website#616]
https://github.com/sbt/sbt/releases/tag/v1.1.1 is out (and tweeted/blogged about https://twitter.com/scala_sbt/status/961704366037225472) but it's not the latest version:

https://www.scala-sbt.org/download.html

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/website/pull/618

**Comment by SethTisue** [comment]
same now for 1.1.2 https://www.scala-sbt.org/download.html

**Comment by dwijnand** [comment]
fixed in #651
