### ISSUE TITLE
Section outdated: Referring to scopes in a build definition

### ISSUE THREAD

**Issue by ankitkariryaa** [sbt/website#633]
Most of examples for the [Scopes](https://www.scala-sbt.org/1.x/docs/Scopes.html) documentation are invalid now!
Starting from [Referring to scopes in a build definition](https://www.scala-sbt.org/1.x/docs/Scopes.html#Referring+to+scopes+in+a+build+definition) to [Inspecting scopes](https://www.scala-sbt.org/1.x/docs/Scopes.html#Inspecting+scopes).

**Comment by dwijnand** [comment]
what do you mean by invalid?

**Comment by ankitkariryaa** [comment]
The examples on the page can't be run. Running the example from [Inspecting scopes](https://www.scala-sbt.org/1.x/docs/Scopes.html#Inspecting+scopes) throws the following error:
```
sbt:ProjectName> inspect Test / fullClasspath
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: Test (similar: test, testOnly, state)
[error] inspect Test / fullClasspath
[error]
```

**Comment by dwijnand** [comment]
you must be using an older version of sbt: that syntax was introduced in sbt 1.1.0 and the docs were updated for that.

```scala
> inspect Test / fullClasspath
[info] Task: scala.collection.Seq[sbt.internal.util.Attributed[java.io.File]]
[info] Description:
[info] 	The exported classpath, consisting of build products and unmanaged and managed, internal and external dependencies.
[info] Provided by:
[info] 	ProjectRef(uri("file:/s/t-inspect/"), "t") / Test / fullClasspath
```
