### ISSUE TITLE
Contents (on sbt Reference Manual page )   as sidebar would be convenient for users

### ISSUE THREAD

**Issue by mrveera** [sbt/website#647]
A sidebar would be more convenient for navigating through the reference manual instead of scrolling all the down to jump into other pages and generally docs and reference manuals use side menu for navigation.
Ref:-https://www.scala-sbt.org/1.x/docs/

**Comment by eed3si9n** [comment]
I've been thinking the same.

**Comment by SethTisue** [comment]
I've always wanted this.

**Comment by dwijnand** [comment]
:100: from me too.

it's [pamphlet](http://www.foundweekends.org/pamflet/)'s default that doesn't work well for reference guides.

**Comment by eed3si9n** [comment]
This was fixed in https://eed3si9n.com/pamflet-080
