### ISSUE TITLE
java.io.IOException: CreateFile() failed with error 3

### ISSUE THREAD

**Issue by littlejiao** [sbt/website#650]
hi，
When I input 'sbt' on cmd, there are some mistakes like this. 
![image](https://user-images.githubusercontent.com/35133062/38078232-3059294e-336e-11e8-9274-9c88904a163f.png)
Can you help me to fix it?
Thank you!

**Comment by SethTisue** [comment]
this doesn't seem like an sbt/website issue

**Comment by eed3si9n** [comment]
It's a duplicate of https://github.com/sbt/sbt/issues/3972. Please use `sbt -Dsbt.io.jdktimestamps=true` for now.
