### ISSUE TITLE
Write cookbook section

### ISSUE THREAD

**Issue by dwijnand** [sbt/website#658]
for example, see https://www.scalawilliam.com/essential-sbt/

another example I've used in the past (because I've found it explains better than the current docs do currently): https://www.playframework.com/documentation/2.6.x/PlayConsole

**Comment by SethTisue** [comment]
fyi @ScalaWilliam, I give out this link all the time

**Comment by lejoow** [comment]
One more upvote for https://www.scalawilliam.com/essential-sbt/ of @ScalaWilliam.

**Comment by dwijnand** [comment]
On a similar note: add (either inline or link) more example builds?

Generally useful in other domains.

**Comment by eed3si9n** [comment]
I am going to do this. Today.
