### ISSUE TITLE
Link examples to sections of the reference guide

### ISSUE THREAD

**Issue by dwijnand** [sbt/website#677]
From @gabro's https://twitter.com/gabro27/status/997815925041704960

> Have you considered linking to the pertinent documentation section in between examples, so that people can get quickly to the details if they like?

**Comment by eed3si9n** [comment]
It would be good to style the reference links to indicate so that they don't have to read it initially.

<details>
 <summary>Maybe using mechanism like this</summary>
Link to more details.
</details>

**Comment by dwijnand** [comment]
If you mean to not distract the user, I agree. But a clickable collapse-thingy is distracting because the user's is drawn to clicking it.

Maybe we can link the section title, or maybe a clickable icon like https://octicons.github.com/icon/book/.

**Comment by gabro** [comment]
Something like a quote block, with a standard structure would be good imho. A simple icon would easily go unnoticed. Something like:

> 📖 Learn about *topic at hand* in the [docs](https://example.com)

**Comment by gabro** [comment]
A concrete example:

---

### Set ThisBuild / scalaVersion from sbt shell

```
sbt:foo-build> set ThisBuild / scalaVersion := "2.12.6"
[info] Defining ThisBuild / scalaVersion
```

Check the `scalaVersion` setting:

```
sbt:foo-build> scalaVersion
[info] 2.12.6
```

> 📖 Learn about *ThisBuild* and the other *Scopes* in the [documentation](https://www.scala-sbt.org/1.x/docs/Scopes.html)
