### ISSUE TITLE
Broken "Edit" link in header

### ISSUE THREAD

**Issue by aaabramov** [sbt/website#721]
Let's take the following page:
https://www.scala-sbt.org/1.x/docs/Multi-Project.html

On top it has "Edit" options which should point to the blob on GitHub:
![image](https://user-images.githubusercontent.com/11317222/45669357-8472c480-bb28-11e8-8224-35b788429646.png)
Currently, it point to https://github.com/sbt/website/edit/1.x/src/reference/00-Getting-Started/05B-Multi-Project.md, but it returns 404.

**Comment by aaabramov** [comment]
I believe it should point to https://github.com/sbt/website/blob/5524bb3e66a67fd73555910519abff51115fe3cd/src/reference/00-Getting-Started/05B-Multi-Project.md

**Comment by eed3si9n** [comment]
Thanks for the report. It should be https://github.com/sbt/website/edit/develop/src/reference/00-Getting-Started/05B-Multi-Project.md
We recently renamed 1.x branch to develop branch.
