### ISSUE TITLE
Download sbt package url link doesn't work anymore

### ISSUE THREAD

**Issue by AndersonChoi** [sbt/website#729]
# Problem
Download sbt package url link doesn't work anymore.
Url link start : https://piccolo.link/

# Example
https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Mac.html -> Download ZIP or TGZ package link doesn't work
https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Windows.html -> Download ZIP or TGZ package and msi installer link doesn't work

**Comment by mrveera** [comment]
Comment by @cunei on sbt/sbt#4165
Regarding the recent download issues, the provider for piccolo.link identified and fixed a load balancing issue, so all should be back to normal. Additional details at: sbt/sbt#4413 (comment)
