### ISSUE TITLE
No pd for sbt 1.x Reference Manual

### ISSUE THREAD

**Issue by reiniersf** [sbt/website#731]
Every time I try to get PDF for 1.x sbt Reference Manual I'm getting a 404 page.

**Comment by SethTisue** [comment]
(the broken link is at https://www.scala-sbt.org/documentation.html, the first "pdf" link on the page)

**Comment by reiniersf** [comment]
exactly, sorry I forget to include that information

**Comment by eed3si9n** [comment]
Sorry I think I published the website from my own laptop instead of using Travis CI, and by default it doesn't build the PDF file, and it wiped it out - https://github.com/sbt/website/blob/ba4c73c142b4dcadcf49a3f1f382fb8e330e3597/build.sbt#L26
Hopefully it will be rebuilt soon since I merged a PR.

**Comment by SethTisue** [comment]
yup, it's up on the site now in glorious Computer Modern

**Comment by SethTisue** [comment]
thank you @reiniersf for the report
