### ISSUE TITLE
The Settings Initialisation page is outdated for version 1.0

### ISSUE THREAD

**Issue by misja-alma** [sbt/website#770]
The page https://www.scala-sbt.org/1.0/docs/Setting-Initialization.html is outdated. 
The code snippets that refer to extending the Build class or the settingsSets method don't compile. I guess these are still from version 0.13 and were not updated for the code changes in 1.0.

E.g. the following snippet contains 3 compile errors when using sbt 1.x:

`import sbt._
import Keys._

import AddSettings._

object MyOwnOrder extends Build {
  // here we load config from a txt file.
  lazy val root = project.in(file(".")).settingSets( autoPlugins, buildScalaFiles, sbtFiles(file("silly.txt")) )
}`

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/website/pull/830
