### ISSUE TITLE
Documentation link leads to a 404 page

### ISSUE THREAD

**Issue by maseev** [sbt/website#783]
On this page (https://www.scala-sbt.org/1.x/docs/Library-Dependencies.html), if you click on the Configuration link in the libraryDependencies section (https://www.scala-sbt.org/1.x/docs/Library-Dependencies.html#The++key), you'll be redirected to the following page (https://www.scala-sbt.org/1.x/sxr/sbt/Configuration.scala.html#sbt.Configuration) which doesn't exist.

**Comment by eed3si9n** [comment]
Thanks for the report!
