### ISSUE TITLE
https://www.scala-sbt.org/downloads.html

### ISSUE THREAD

**Issue by cheevo** [sbt/website#788]
404: PAGE NOT FOUND https://www.scala-sbt.org/downloads.html

**Comment by cheevo** [comment]
also https://www.scala-sbt.org/1.0/docs/Migrating-from-sbt-012x.html

**Comment by eed3si9n** [comment]
- https://www.scala-sbt.org/download.html
- https://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html
