### ISSUE TITLE
it should be ~(whitespace)compile

### ISSUE THREAD

**Issue by gusega** [sbt/website#877]
Hello, on the https://www.scala-sbt.org/1.x/docs/sbt-by-example.html page, it uses everywhere `~command` but actually it should be `~ command` (with whitespace). At least on windows, the version without whitespace does not work. (Also in the help documentation of sbt it says `~ <command>` (also with whitespace))

**Comment by eed3si9n** [comment]
It works for me on Windows.

<img width="640" alt="Windows_7_64bit__2017-12-13_Java_8___Running_" src="https://user-images.githubusercontent.com/184683/75272444-e890c200-57cb-11ea-9811-96c8fb19ca1d.png">

**Comment by gusega** [comment]
It works once, but if you change the code it is not 're compiled automatically, but it should.

**Comment by eed3si9n** [comment]
If there's a file watching issue on Windows, that should be reported to sbt/sbt as a bug. I don't think that's a website documentation issue.

**Comment by gusega** [comment]
Full story. I used it from git bash command line on win 10. If you put whitespace between  wave symbol and "compile" the it recompiles on changes. If you don't put whitespace the it compiles only once but does not react on subsequent changes. Funny, for "testQuick" command, it works as expected both with and without space between. I think that it is a documentation issue as well because if you type "help" then you will see that there there is a whitespace between wave symbol and the command. So I think documentation on the website should be in line with documentation in the command line help (disregarding of whether something works or not). Thanks.

**Comment by gusega** [comment]
Sorry that's my stupidity. That works fine. It is correct and issue can be closed. Thanks.
