### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by mjuanes** [sbt/website#880]
Here : https://www.scala-sbt.org/1.x/docs/Resolvers.html#Custom+resolvers

These:
https://www.scala-sbt.org/1.x/api/sbt/librarymanagement/ResolverFunctions$file$.html

**Comment by eed3si9n** [comment]
@mjuanes Thanks for the report. Looks like it's https://www.scala-sbt.org/1.3.8/api/sbt/librarymanagement/Resolver$.html#file.
