### ISSUE TITLE
Broken manual installation page link

### ISSUE THREAD

**Issue by dedifferentiator** [sbt/website#940]
#### Reproduction:
 - Visit https://scala-android.org/setup/#manual page
 - Choose manual installation option at prerequisites
 - Open http://www.scala-sbt.org/0.13/docs/Manual-Installation.html which turns out broken.

**Comment by eed3si9n** [comment]
Not sure when we deleted it since we don't want ppl to do what was documented in the page, which was to roll your own bash script.
A better step would be to grab the latest tgz file from here - https://www.scala-sbt.org/download.html
