### ISSUE TITLE
Join algolia's DocSearch program

### ISSUE THREAD

**Issue by keynmol** [sbt/website#962]
I think SBT's docs are great but underappreciated - a search bar with instant response can go a long way in helping that.

I know that scala-lang.org is using https://docsearch.algolia.com/ (a free search program for significant open source projects). The PR to add it in is small: https://github.com/scala/docs.scala-lang/pull/1096/files

Creating this issue just to track, there are some actions:

1. A maintainer to request Algolia API key
2. Me to create a PR with HTML necessary for algolia to work

How does this sound?

**Comment by eed3si9n** [comment]
@keynmol Sounds awesome.

**Comment by SethTisue** [comment]
I would use this often. currently I `git clone` and `git grep` this repo to find stuff (and I do that several times a week, minimum)

**Comment by keynmol** [comment]
I'm making good progress - apparently just stealing the code from scala-lang allows me to see **some** search results while I work on the rendering.

@eed3si9n is there a way to make `makeSite` snappier while losing some pages may be? I mostly work on the layouts and templates and it takes a minute to render all the docs, which at this point I don't need

**Comment by eed3si9n** [comment]
@keynmol If you care only about front pages you can turn off Pamflet as follows:

```diff
diff --git a/build.sbt b/build.sbt
index dd921bd5..8ad5c0f5 100644
--- a/build.sbt
+++ b/build.sbt
@@ -9,8 +9,9 @@ ThisBuild / scalafmtOnCompile := true

 lazy val root = (project in file("."))
   .enablePlugins(
-    (if (!isBetaBranch) Seq(ParadoxSitePlugin) else Seq()) ++
-      Seq(LowTechSnippetPamfletPlugin, ScriptedPlugin): _*
+    ParadoxSitePlugin, ScriptedPlugin
+    // (if (!isBetaBranch) Seq(ParadoxSitePlugin) else Seq()) ++
+    //   Seq(LowTechSnippetPamfletPlugin, ScriptedPlugin): _*
   )
   .settings(
     name := "website",
@@ -44,10 +45,10 @@ lazy val root = (project in file("."))
     SiteHelpers.addMappingsToSiteDir(mappings in RedirectTutorial, tutorialSubDirName),
     // GitHub Pages. See project/Docs.scala
     customGhPagesSettings,
-    mappings in Pamflet := {
-      val xs = (mappings in Pamflet).value
-      Pdf.cleanupCombinedPages(xs) ++ xs
-    },
+    // mappings in Pamflet := {
+    //   val xs = (mappings in Pamflet).value
+    //   Pdf.cleanupCombinedPages(xs) ++ xs
+    // },
     if (scala.sys.BooleanProp.keyExists("sbt.website.generate_pdf"))
       Def settings (
         // NOTE - PDF settings must be done externally like this because pdf generation generically looks
```

**Comment by keynmol** [comment]
@eed3si9n this worked for landing pages but once I realised that layout is completely different in the docs I had to revert that.

I've added a provisional PR with Algolia's default theme, and I hope we can iterate from there

**Comment by keynmol** [comment]
For anyone following the issue and not the PR - progress is happening :) 

Just a couple of optional tweaks to Algolia configuration and we should be in a good place.

![image](https://user-images.githubusercontent.com/1052965/101077523-da62a400-359c-11eb-985d-aee731ac6f5c.png)
