### ISSUE TITLE
Add in a section about sbt BSP server and differentiate it from current server page.

### ISSUE THREAD

**Issue by ckipp01** [sbt/website#965]
Something I've seen a few Metals users stumble on (and I've done it myself before), is to assume that the [sbt-server page](https://www.scala-sbt.org/1.x/docs/sbt-server.html) is where they should look for information about the sbt BSP server. Even though I know this page is about the LSP server, I've even accidentally linked this before when quickly searching the sbt sidebar and I see `server` and I assume this is what I want.

I'm not sure what the status of the sbt server is, but it would be great to have a specific page about the sbt BSP server and make it very clearly differentiated by the current `sbt-server` page.

**Comment by eed3si9n** [comment]
I think we should keep using sbt server page, but put relevant information about BSP.

**Comment by eed3si9n** [comment]
I've added Metals instruction on the same page - https://github.com/sbt/website/pull/980
